<?php

/**
 * BaseStudentGroupLessons
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $student_group_id
 * @property integer $lesson_id
 * @property StudentGroup $StudentGroup
 * @property Lesson $Lesson
 * 
 * @method integer             getStudentGroupId()   Returns the current record's "student_group_id" value
 * @method integer             getLessonId()         Returns the current record's "lesson_id" value
 * @method StudentGroup        getStudentGroup()     Returns the current record's "StudentGroup" value
 * @method Lesson              getLesson()           Returns the current record's "Lesson" value
 * @method StudentGroupLessons setStudentGroupId()   Sets the current record's "student_group_id" value
 * @method StudentGroupLessons setLessonId()         Sets the current record's "lesson_id" value
 * @method StudentGroupLessons setStudentGroup()     Sets the current record's "StudentGroup" value
 * @method StudentGroupLessons setLesson()           Sets the current record's "Lesson" value
 * 
 * @package    candle
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseStudentGroupLessons extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student_group_lessons');
        $this->hasColumn('student_group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('lesson_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('StudentGroup', array(
             'local' => 'student_group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Lesson', array(
             'local' => 'lesson_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}