<?php

/**
 * BaseStudentGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Lessons
 * @property Doctrine_Collection $StudentGroupLessons
 * 
 * @method string              getName()                Returns the current record's "name" value
 * @method Doctrine_Collection getLessons()             Returns the current record's "Lessons" collection
 * @method Doctrine_Collection getStudentGroupLessons() Returns the current record's "StudentGroupLessons" collection
 * @method StudentGroup        setName()                Sets the current record's "name" value
 * @method StudentGroup        setLessons()             Sets the current record's "Lessons" collection
 * @method StudentGroup        setStudentGroupLessons() Sets the current record's "StudentGroupLessons" collection
 * 
 * @package    candle
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStudentGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student_group');
        $this->hasColumn('name', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));


        $this->index('name_index', array(
             'fields' => 'name',
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Lesson as Lessons', array(
             'refClass' => 'StudentGroupLessons',
             'local' => 'student_group_id',
             'foreign' => 'lesson_id'));

        $this->hasMany('StudentGroupLessons', array(
             'local' => 'id',
             'foreign' => 'student_group_id'));
    }
}