<?php

/**
 * BaseLinkedLessons
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $lesson1_id
 * @property integer $lesson2_id
 * 
 * @method integer       getLesson1Id()  Returns the current record's "lesson1_id" value
 * @method integer       getLesson2Id()  Returns the current record's "lesson2_id" value
 * @method LinkedLessons setLesson1Id()  Sets the current record's "lesson1_id" value
 * @method LinkedLessons setLesson2Id()  Sets the current record's "lesson2_id" value
 * 
 * @package    candle
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseLinkedLessons extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('linked_lessons');
        $this->hasColumn('lesson1_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('lesson2_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}