<?php

/**
 * BaseRoomType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $code
 * @property Doctrine_Collection $Room
 * 
 * @method string              getName() Returns the current record's "name" value
 * @method string              getCode() Returns the current record's "code" value
 * @method Doctrine_Collection getRoom() Returns the current record's "Room" collection
 * @method RoomType            setName() Sets the current record's "name" value
 * @method RoomType            setCode() Sets the current record's "code" value
 * @method RoomType            setRoom() Sets the current record's "Room" collection
 * 
 * @package    candle
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseRoomType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('room_type');
        $this->hasColumn('name', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('code', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Room', array(
             'local' => 'id',
             'foreign' => 'room_type_id'));
    }
}