<?php

/**
 * BaseUserTimetableLessons
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_timetable_id
 * @property integer $lesson_id
 * @property boolean $highlighted
 * @property UserTimetable $UserTimetable
 * @property Lesson $Lesson
 * 
 * @method integer              getUserTimetableId()   Returns the current record's "user_timetable_id" value
 * @method integer              getLessonId()          Returns the current record's "lesson_id" value
 * @method boolean              getHighlighted()       Returns the current record's "highlighted" value
 * @method UserTimetable        getUserTimetable()     Returns the current record's "UserTimetable" value
 * @method Lesson               getLesson()            Returns the current record's "Lesson" value
 * @method UserTimetableLessons setUserTimetableId()   Sets the current record's "user_timetable_id" value
 * @method UserTimetableLessons setLessonId()          Sets the current record's "lesson_id" value
 * @method UserTimetableLessons setHighlighted()       Sets the current record's "highlighted" value
 * @method UserTimetableLessons setUserTimetable()     Sets the current record's "UserTimetable" value
 * @method UserTimetableLessons setLesson()            Sets the current record's "Lesson" value
 * 
 * @package    candle
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserTimetableLessons extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_timetable_lessons');
        $this->hasColumn('user_timetable_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('lesson_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('highlighted', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UserTimetable', array(
             'local' => 'user_timetable_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Lesson', array(
             'local' => 'lesson_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}