<?php

/**
 * BaseTeacher
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $given_name
 * @property string $family_name
 * @property string $iniciala
 * @property string $oddelenie
 * @property string $katedra
 * @property string $external_id
 * @property Doctrine_Collection $Lesson
 * @property Doctrine_Collection $TeacherLessons
 * 
 * @method string              getGivenName()      Returns the current record's "given_name" value
 * @method string              getFamilyName()     Returns the current record's "family_name" value
 * @method string              getIniciala()       Returns the current record's "iniciala" value
 * @method string              getOddelenie()      Returns the current record's "oddelenie" value
 * @method string              getKatedra()        Returns the current record's "katedra" value
 * @method string              getExternalId()     Returns the current record's "external_id" value
 * @method Doctrine_Collection getLesson()         Returns the current record's "Lesson" collection
 * @method Doctrine_Collection getTeacherLessons() Returns the current record's "TeacherLessons" collection
 * @method Teacher             setGivenName()      Sets the current record's "given_name" value
 * @method Teacher             setFamilyName()     Sets the current record's "family_name" value
 * @method Teacher             setIniciala()       Sets the current record's "iniciala" value
 * @method Teacher             setOddelenie()      Sets the current record's "oddelenie" value
 * @method Teacher             setKatedra()        Sets the current record's "katedra" value
 * @method Teacher             setExternalId()     Sets the current record's "external_id" value
 * @method Teacher             setLesson()         Sets the current record's "Lesson" collection
 * @method Teacher             setTeacherLessons() Sets the current record's "TeacherLessons" collection
 * 
 * @package    candle
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTeacher extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('teacher');
        $this->hasColumn('given_name', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('family_name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('iniciala', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('oddelenie', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('katedra', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('external_id', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Lesson', array(
             'refClass' => 'TeacherLessons',
             'local' => 'teacher_id',
             'foreign' => 'lesson_id'));

        $this->hasMany('TeacherLessons', array(
             'local' => 'id',
             'foreign' => 'teacher_id'));
    }
}