<?php

/**
 * BaseTeacherLessons
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $teacher_id
 * @property integer $lesson_id
 * @property Teacher $Teacher
 * @property Lesson $Lesson
 * 
 * @method integer        getTeacherId()  Returns the current record's "teacher_id" value
 * @method integer        getLessonId()   Returns the current record's "lesson_id" value
 * @method Teacher        getTeacher()    Returns the current record's "Teacher" value
 * @method Lesson         getLesson()     Returns the current record's "Lesson" value
 * @method TeacherLessons setTeacherId()  Sets the current record's "teacher_id" value
 * @method TeacherLessons setLessonId()   Sets the current record's "lesson_id" value
 * @method TeacherLessons setTeacher()    Sets the current record's "Teacher" value
 * @method TeacherLessons setLesson()     Sets the current record's "Lesson" value
 * 
 * @package    candle
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTeacherLessons extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('teacher_lessons');
        $this->hasColumn('teacher_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('lesson_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Teacher', array(
             'local' => 'teacher_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Lesson', array(
             'local' => 'lesson_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}