<?php

/**
 * BaseLessonType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $code
 * @property Doctrine_Collection $Lesson
 * 
 * @method string              getName()   Returns the current record's "name" value
 * @method string              getCode()   Returns the current record's "code" value
 * @method Doctrine_Collection getLesson() Returns the current record's "Lesson" collection
 * @method LessonType          setName()   Sets the current record's "name" value
 * @method LessonType          setCode()   Sets the current record's "code" value
 * @method LessonType          setLesson() Sets the current record's "Lesson" collection
 * 
 * @package    candle
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLessonType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lesson_type');
        $this->hasColumn('name', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('code', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Lesson', array(
             'local' => 'id',
             'foreign' => 'lesson_type_id'));
    }
}