<?php

/**
 * BaseRoom
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $room_type_id
 * @property integer $capacity
 * @property RoomType $RoomType
 * @property Doctrine_Collection $Lesson
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method integer             getRoomTypeId()   Returns the current record's "room_type_id" value
 * @method integer             getCapacity()     Returns the current record's "capacity" value
 * @method RoomType            getRoomType()     Returns the current record's "RoomType" value
 * @method Doctrine_Collection getLesson()       Returns the current record's "Lesson" collection
 * @method Room                setName()         Sets the current record's "name" value
 * @method Room                setRoomTypeId()   Sets the current record's "room_type_id" value
 * @method Room                setCapacity()     Sets the current record's "capacity" value
 * @method Room                setRoomType()     Sets the current record's "RoomType" value
 * @method Room                setLesson()       Sets the current record's "Lesson" collection
 * 
 * @package    candle
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseRoom extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('room');
        $this->hasColumn('name', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('room_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('capacity', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RoomType', array(
             'local' => 'room_type_id',
             'foreign' => 'id'));

        $this->hasMany('Lesson', array(
             'local' => 'id',
             'foreign' => 'room_id'));
    }
}