<?php

/**
 * BaseSubject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $code
 * @property string $short_code
 * @property Doctrine_Collection $Lesson
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method string              getCode()       Returns the current record's "code" value
 * @method string              getShortCode()  Returns the current record's "short_code" value
 * @method Doctrine_Collection getLesson()     Returns the current record's "Lesson" collection
 * @method Subject             setName()       Sets the current record's "name" value
 * @method Subject             setCode()       Sets the current record's "code" value
 * @method Subject             setShortCode()  Sets the current record's "short_code" value
 * @method Subject             setLesson()     Sets the current record's "Lesson" collection
 * 
 * @package    candle
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseSubject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subject');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('code', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('short_code', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '10',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Lesson', array(
             'local' => 'id',
             'foreign' => 'subject_id'));
    }
}