<?php

/**
 * BaseDataUpdate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property datetime $datetime
 * @property string $description
 * 
 * @method datetime   getDatetime()    Returns the current record's "datetime" value
 * @method string     getDescription() Returns the current record's "description" value
 * @method DataUpdate setDatetime()    Sets the current record's "datetime" value
 * @method DataUpdate setDescription() Sets the current record's "description" value
 * 
 * @package    candle
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDataUpdate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('data_update');
        $this->hasColumn('datetime', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}