<?php

/**
 * BaseUserTimetableLessons
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_timetable_id
 * @property integer $lesson_id
 * @property boolean $selected
 * 
 * @method integer              getUserTimetableId()   Returns the current record's "user_timetable_id" value
 * @method integer              getLessonId()          Returns the current record's "lesson_id" value
 * @method boolean              getSelected()          Returns the current record's "selected" value
 * @method UserTimetableLessons setUserTimetableId()   Sets the current record's "user_timetable_id" value
 * @method UserTimetableLessons setLessonId()          Sets the current record's "lesson_id" value
 * @method UserTimetableLessons setSelected()          Sets the current record's "selected" value
 * 
 * @package    candle
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUserTimetableLessons extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_timetable_lessons');
        $this->hasColumn('user_timetable_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('lesson_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('selected', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}