<?php

/**
 * BaseDataUpdate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property datetime $datetime
 * @property string $description
 * @property datetime $version
 * @property string $semester
 * @property integer $school_year_low
 * 
 * @method datetime   getDatetime()        Returns the current record's "datetime" value
 * @method string     getDescription()     Returns the current record's "description" value
 * @method datetime   getVersion()         Returns the current record's "version" value
 * @method string     getSemester()        Returns the current record's "semester" value
 * @method integer    getSchoolYearLow()   Returns the current record's "school_year_low" value
 * @method DataUpdate setDatetime()        Sets the current record's "datetime" value
 * @method DataUpdate setDescription()     Sets the current record's "description" value
 * @method DataUpdate setVersion()         Sets the current record's "version" value
 * @method DataUpdate setSemester()        Sets the current record's "semester" value
 * @method DataUpdate setSchoolYearLow()   Sets the current record's "school_year_low" value
 * 
 * @package    candle
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDataUpdate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('data_update');
        $this->hasColumn('datetime', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('version', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));
        $this->hasColumn('semester', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('school_year_low', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}