<?php

/**
 * BaseSubject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $code
 * @property string $short_code
 * @property integer $credit_value
 * @property string $rozsah
 * @property string $external_id
 * @property Doctrine_Collection $Lessons
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getCode()         Returns the current record's "code" value
 * @method string              getShortCode()    Returns the current record's "short_code" value
 * @method integer             getCreditValue()  Returns the current record's "credit_value" value
 * @method string              getRozsah()       Returns the current record's "rozsah" value
 * @method string              getExternalId()   Returns the current record's "external_id" value
 * @method Doctrine_Collection getLessons()      Returns the current record's "Lessons" collection
 * @method Subject             setName()         Sets the current record's "name" value
 * @method Subject             setCode()         Sets the current record's "code" value
 * @method Subject             setShortCode()    Sets the current record's "short_code" value
 * @method Subject             setCreditValue()  Sets the current record's "credit_value" value
 * @method Subject             setRozsah()       Sets the current record's "rozsah" value
 * @method Subject             setExternalId()   Sets the current record's "external_id" value
 * @method Subject             setLessons()      Sets the current record's "Lessons" collection
 * 
 * @package    candle
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseSubject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subject');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('code', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('short_code', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '20',
             ));
        $this->hasColumn('credit_value', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('rozsah', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('external_id', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Lesson as Lessons', array(
             'local' => 'id',
             'foreign' => 'subject_id'));
    }
}