<?php

/**
 * BaseRoom
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $room_type_id
 * @property integer $capacity
 * @property RoomType $RoomType
 * @property Doctrine_Collection $Lesson
 * @property Doctrine_Collection $FreeRoomInterval
 * 
 * @method string              getName()             Returns the current record's "name" value
 * @method integer             getRoomTypeId()       Returns the current record's "room_type_id" value
 * @method integer             getCapacity()         Returns the current record's "capacity" value
 * @method RoomType            getRoomType()         Returns the current record's "RoomType" value
 * @method Doctrine_Collection getLesson()           Returns the current record's "Lesson" collection
 * @method Doctrine_Collection getFreeRoomInterval() Returns the current record's "FreeRoomInterval" collection
 * @method Room                setName()             Sets the current record's "name" value
 * @method Room                setRoomTypeId()       Sets the current record's "room_type_id" value
 * @method Room                setCapacity()         Sets the current record's "capacity" value
 * @method Room                setRoomType()         Sets the current record's "RoomType" value
 * @method Room                setLesson()           Sets the current record's "Lesson" collection
 * @method Room                setFreeRoomInterval() Sets the current record's "FreeRoomInterval" collection
 * 
 * @package    candle
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRoom extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('room');
        $this->hasColumn('name', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('room_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('capacity', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('external_id_index', array(
             'fields' => 'name',
             'type' => 'unique',
             ));
        $this->index('name_index', array(
             'fields' => 'name',
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RoomType', array(
             'local' => 'room_type_id',
             'foreign' => 'id'));

        $this->hasMany('Lesson', array(
             'local' => 'id',
             'foreign' => 'room_id'));

        $this->hasMany('FreeRoomInterval', array(
             'local' => 'id',
             'foreign' => 'room_id'));
    }
}