<?php

/**
 * Lesson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    candle
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Lesson extends BaseLesson
{
    public function getTeachers(Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()
                ->from('Teacher t')
                ->innerJoin('t.TeacherLessons tl');
        }
        
        $q->andWhere('tl.lesson_id = ?', $this->getId());
        return $q->execute();
    }
    
    public function getRoom() {
        $q = Doctrine_Query::create()
            ->from('Room r')
            ->andWhere('r.id = ?', $this->getRoomId());
        return $q->fetchOne();
    }
    
    public function getType() {
        $q = Doctrine_Query::create()
            ->from('LessonType t')
            ->andWhere('t.id = ?', $this->getLessonTypeId());
        return $q->fetchOne();
    }
}
