<?php

/**
 * Subject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    candle
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Subject extends BaseSubject
{
    public function getLessons() {
        $q = Doctrine_Query::create()
            ->from('Lesson l')
            ->where('l.subject_id = ?', $this->getId());
        
        return Doctrine_Core::getTable('Lesson')->getLessons($q);
    }
}
