<?php

/**
 * Teacher
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    candle
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Teacher extends BaseTeacher
{
    function __toString() {
        return $this->getGivenName().' '.$this->getFamilyName();
    }
    
    function getShortName() {
        return ($this->getGivenName()?substr($this->getGivenName(), 0, 1).'. ':'').$this->getFamilyName();
    }
}
