# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  # style.css sa kompiluje zo zdrojov v web/scss (pozri README.md)
  stylesheets:    [font-awesome.min.css { media: all }, style.css { media: all }, print.css { media: print }, tty.css { media: tty }, popup.css]

  javascripts:    [mootools-1.2.4-core.js, element.js, layout.js, timetable_editor.js, timetable.js, search.js, popup.js]

  has_layout:     true
  layout:         layout
